language: python
python:
- '2.7'
install:
- nvm install 6.1
- nvm use 6.1
- rvm install 2.1
- gem install sass
- pip install --upgrade pip
- pip install lektor
- npm install -g grunt
- npm install
- npm run build
script:
- lektor build
deploy:
  provider: script
  script: lektor deploy ghpages
